# Generated by Django 5.0.7 on 2024-07-30 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('games', '0001_initial'),
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clips',
            field=models.ManyToManyField(blank=True, related_name='user_clips', to='streams.clip'),
        ),
        migrations.AddField(
            model_name='user',
            name='download_games',
            field=models.ManyToManyField(blank=True, related_name='download_users', to='games.games'),
        ),
        migrations.AddField(
            model_name='user',
            name='friends_online',
            field=models.ManyToManyField(blank=True, related_name='user_friends_online', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='live_streams',
            field=models.ManyToManyField(blank=True, related_name='user_live_streams', to='streams.stream'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
